// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using colanta_backend.App.Shared.Infraestructure;

namespace colanta_backend.Migrations
{
    [DbContext(typeof(colantaContext))]
    [Migration("20220328011620_Initial-Create")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("colanta_backend.App.Brands.Infraestructure.EFBrand", b =>
                {
                    b.Property<int?>("id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("id_siesa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("id_siesa");

                    b.Property<int?>("id_vtex")
                        .HasColumnType("int")
                        .HasColumnName("id_vtex");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("name");

                    b.Property<short?>("state")
                        .HasColumnType("smallint")
                        .HasColumnName("state");

                    b.HasKey("id");

                    b.ToTable("brands");
                });

            modelBuilder.Entity("colanta_backend.App.Brands.Infraestructure.EFDeltaBrand", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("siesa_id")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("DeltaBrands");
                });

            modelBuilder.Entity("colanta_backend.App.Shared.Infraestructure.EFProcess", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("dateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("dateTime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("json_details")
                        .HasColumnType("text")
                        .HasColumnName("json_details");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<int>("total_errors")
                        .HasColumnType("int")
                        .HasColumnName("total_errors");

                    b.Property<int>("total_loads")
                        .HasColumnType("int")
                        .HasColumnName("total_loads");

                    b.Property<int>("total_not_procecced")
                        .HasColumnType("int")
                        .HasColumnName("total_not_procecced");

                    b.HasKey("id");

                    b.ToTable("Process");
                });
#pragma warning restore 612, 618
        }
    }
}
